### ISSUE TITLE
nfc correctifs

### ISSUE THREAD

**Issue by baud123** [ThomasGsp/sunlab#1]
- corriger le lien de « Trouver l'ID de sa carte » sur http://porte.mysunlab.org/common/user_admin.php  vers nfc.mysunlab.org
- sur http://nfc.mysunlab.org faire pointer le lien index vers http://presence.mysunlab.org
- revoir le title sur la page de déconnexion (remplacer « Login » par « Au revoir ! »)

**Comment by ThomasGsp** [comment]
Corrections appliqués dans: https://github.com/ThomasGsp/sunlab/commit/eaf85ccb618481e03bb67ba50636962702e87d09
